apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Alertmanager"
spec:
  type: NodePort
  ports:
  - port: 9093
    targetPort: 9093
    #nodePort: 30004
  selector:
    k8s-app: alertmanager 

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-alertmanager
  namespace: kube-system
spec:
  rules:
  - host: alertmanager.k8s.dapp.com
    http:
      paths:
      - backend:
          serviceName: alertmanager
          servicePort: 9093