apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Alertmanager"
spec:
  type: NodePort
  ports:
  - port: 9093
    targetPort: 9093
    nodePort: 30004
  selector:
    k8s-app: alertmanager 

---

apiVersion: v1
kind: Service
metadata:
  name: am-cluster-peer1
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Alertmanager"
spec:
  ports:
  - port: 9094
    targetPort: 9094
  selector:
    k8s-app-instance: alertmanager1	

---

apiVersion: v1
kind: Service
metadata:
  name: am-cluster-peer2
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Alertmanager"
spec:
  ports:
  - port: 9094
    targetPort: 9094
  selector:
    k8s-app-instance: alertmanager2