apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: tracker-test
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 4h
      group_by: [alertname]
      routes:
      - receiver: tracker-test
        group_wait: 30s
        group_by: [app]
        match:
          severity: warning
    receivers:
    - name: tracker-test
      webhook_configs:
      - url: 'http://trackerproxy.k8s.dapp.com/tracker'
        send_resolved: false