apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  rules.yml: |
    groups:
    - name: k8s.rules
      rules:
      - expr: sum(rate(container_cpu_usage_seconds_total{container_name=~"^[0-9]{1,11}$"}[1m])) by (container_name, pod_name) / on (pod_name) group_left label_replace(kube_pod_container_resource_limits_cpu_cores{container=~"^[0-9]{1,11}$"}, "pod_name", "$1", "pod", "(.*)") *100
        record: rule:dd_app:pod_cpu_usage
      - expr: sum(container_memory_usage_bytes{container_name=~"^[0-9]{1,11}$"}) by (container_name, pod_name) / on (pod_name) group_left label_replace(kube_pod_container_resource_limits_memory_bytes{container=~"^[0-9]{1,11}$"}, "pod_name", "$1", "pod", "(.*)") *100
        record: rule:dd_app:pod_mem_usage
      - expr: sum by (pod) (kube_pod_status_phase{pod=~"^[0-9]{1,11}.+$", phase!~"Running|Succeeded"}) * on(pod) group_left(label_app) kube_pod_labels{pod=~"^[0-9]{1,11}.+$"}
        record: rule:dd_app:pod_status_phase
    - name: k8s-apps
      rules:
      - alert: k8sAppPodRestart
        expr: rate(kube_pod_container_status_restarts_total{container=~"^[0-9]{1,11}$"}[1m]) > 0
        labels:
          severity: warning
          app: "{{$labels.container}}"
        annotations:
          message: '{{ $labels.container }}/{{ $labels.pod }} is restarting'
      - alert: k8sAppPodCPUOvercommit
        expr: rule:dd_app:pod_cpu_usage > 70
        for: 5m
        labels:
          severity: warning
          app: "{{$labels.container_name}}"
        annotations:
          message: '{{ $labels.container_name }}/{{ $labels.pod_name }} overcommited CPU resource requests on Pod. Current value is {{ $value }}'
      - alert: k8sAppPodMemOvercommit
        expr: rule:dd_app:pod_mem_usage > 80
        for: 5m
        labels:
          severity: warning
          app: "{{$labels.container_name}}"
        annotations:
          message: '{{ $labels.container_name }}/{{ $labels.pod_name }} overcommited Memory resource requests on Pod. Current value is {{ $value }}'
      - alert: k8sAppPodRootfsOvercommit
        expr: dd_app_container_rootfs_usage{mounted="/",container_name=~"^[0-9]{1,11}$"} > 60
        labels:
          severity: warning
          app: "{{$labels.container_name}}"
        annotations:
          message: '{{ $labels.container_name }}/{{ $labels.pod_name }} Root FileSystem Usage is over 60%'    
      - alert: k8sAppPodNotReady
        expr: rule:dd_app:pod_status_phase > 0
        for: 10m
        labels:
          severity: warning
          app: "{{$labels.label_app}}"
        annotations:
          message: '{{ $labels.label_app }}/{{ $labels.pod }} is not ready'