apiVersion: v1
kind: Service
metadata:
  name: k8s-tracker-proxy
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "k8s-tracker-proxy"
spec:
  #type: NodePort
  ports:
  - port: 8189
    targetPort: 8189
    #nodePort: 30008
  selector:
    k8s-app: k8s-tracker-proxy

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-tracker-proxy
  namespace: kube-system
spec:
  rules:
  - host: trackerproxy.k8s.dapp.com
    http:
      paths:
      - backend:
          serviceName: k8s-tracker-proxy
          servicePort: 8189