apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
labels:
  k8s-app: prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data    