apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  rules.yml: |
    groups:
    - name: test-rule
      rules:
      - alert: NodeFilesystemUsage
        expr: (node_filesystem_size{device="rootfs"} - node_filesystem_free{device="rootfs"}) / node_filesystem_size{device="rootfs"} * 100 > 80
        for: 2m
        labels:
          team: node
        annotations:
          summary: "{{$labels.instance}}: High Filesystem usage detected"
          description: "{{$labels.instance}}: Filesystem usage is above 80% (current value is: {{ $value }}"
      - alert: NodeMemoryUsage
        expr: (node_memory_MemTotal - (node_memory_MemFree+node_memory_Buffers+node_memory_Cached )) / node_memory_MemTotal * 100 > 80
        for: 2m
        labels:
          team: node
        annotations:
          summary: "{{$labels.instance}}: High Memory usage detected"
          description: "{{$labels.instance}}: Memory usage is above 80% (current value is: {{ $value }}"
      - alert: NodeCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu{kubernetes_name="node-exporter",mode="idle"}[5m])) * 100)) > 80
        for: 2m
        labels:
          team: node
        annotations:
          summary: "{{$labels.instance}}: High CPU usage detected"
          description: "{{$labels.instance}}: CPU usage is above 80% (current value is: {{ $value }}"  
      - alert: AlertTest
        expr: (100 - (avg by (instance) (irate(node_cpu{kubernetes_name="node-exporter",mode="idle"}[5m])) * 100)) > 5
        for: 30s
        labels:
          team: node
          service: k8s
          severity: warning
          external_monitor_id: 2000001
        annotations:
          summary: "{{$labels.instance}}: Alert Test"
          description: "{{$labels.instance}}: Alert Test! CPU usage (current value is: {{ $value }}"
      - alert: AlertTest
              expr: (100 - (avg by (instance) (irate(node_cpu{kubernetes_name="node-exporter",mode="idle"}[5m])) * 100)) > 5
              labels:
                team: node
                service: k8s
                severity: warning
                external_monitor_id: 2000001
              annotations:
                summary: "{{$labels.instance}}: Alert Test"
                description: "{{$labels.instance}}: Alert Test! CPU usage (current value is: {{ $value }}"