apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  ldap.toml: |
    [[servers]]
    host = "idcauth.dangdang.com"
    port = 389
    bind_dn = "cn=ldapcomm,ou=KeWenDangDang,dc=dangdang,dc=com"
    bind_password = "Dell1950"
    search_filter = "(mail=%s)"
    search_base_dns = ["ou=KeWenDangDang,dc=dangdang,dc=com"]
    