apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Grafana"
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8090
    #nodePort: 30005
  selector:
    k8s-app: grafana
    
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: kube-system
spec:
  rules:
  - host: grafana.k8s.dapp.com
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 8090